#include "src/game/envfx_snow.h"

const GeoLayout cr_j355_Fludd_Switch_Option[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -33, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Half__SHOES__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Closed__SHOES__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Dead_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Dead_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, cr_j355_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, cr_j355_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 40, 0, 0, cr_j355_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, cr_j355_Right_Hand_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Right_Hand_Switch_Option_Right_Hand_Cap_mesh_layer_2),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Hand_Switch_Option_Bulb_DL_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 59, 0, 0, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_2),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Bulb_DL_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Capless_Head_Switch_Option_Capless_Head_mesh_layer_7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_7),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 40, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Switch_Option_Right_Hand_Cap_mesh_layer_7),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Switch_Option_Bulb_DL_mesh_layer_7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_7),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Wing_Cap_Switch_Option_Bulb_DL_mesh_layer_7),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Fludd_Switch_Option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -33, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Capless_Head_Switch_Option_Capless_Head_mesh_layer_7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_7),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 40, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Switch_Option_Right_Hand_Cap_mesh_layer_7),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Switch_Option_Bulb_DL_mesh_layer_7),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_7),
		GEO_OPEN_NODE(),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Wing_Cap_Switch_Option_Bulb_DL_mesh_layer_7),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Butt_mesh_layer_7),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Torso_skinned_mesh_layer_7),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 48, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Torso_mesh_layer_7),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, cr_j355_fludd_switch_func),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Fludd_Switch_Option),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Head_DL_mesh_layer_7),
												GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Bulb_DL_mesh_layer_7),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, 63, -7, 10, -148),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Wing_DL_mesh_layer_7),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, -63, 7, -10, -148),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Wing_DL_mesh_layer_7),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -6, 48, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Arm_DL_1_mesh_layer_7),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -2, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Arm_DL_2_mesh_layer_7),
									GEO_CLOSE_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -2, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Arm_DL_3_mesh_layer_7),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Hand_DL_mesh_layer_7),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Left_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -6, -48, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 1),
								GEO_OPEN_NODE(),
									GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Arm_DL_1_mesh_layer_7),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -1, 1),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Arm_DL_2_mesh_layer_7),
									GEO_CLOSE_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -1, 1),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Arm_DL_3_mesh_layer_7),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_DL_mesh_layer_7),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 13, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Open),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Peace),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Cap),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, 37, NULL),
				GEO_OPEN_NODE(),
					GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, -1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Thigh_DL_mesh_layer_7),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Thigh_Color_mesh_layer_7),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 77, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Leg_mesh_layer_7),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 84, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Shoe_mesh_layer_7),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, -37, NULL),
				GEO_OPEN_NODE(),
					GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, 1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Thigh_DL_mesh_layer_7),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Thigh_Color_mesh_layer_7),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 77, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Leg_mesh_layer_7),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Shoe_DL_mesh_layer_7),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_Ice_Robo_Jess[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Butt_mesh_layer_7),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Torso_skinned_mesh_layer_7),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 48, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Torso_mesh_layer_7),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, cr_j355_fludd_switch_func),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, cr_j355_Fludd_Switch_Option),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Head_DL_mesh_layer_7),
														GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Bulb_DL_mesh_layer_7),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Capless_Head),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, 63, -7, 10, -148),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Wing_DL_mesh_layer_7),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, -63, 7, -10, -148),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Wing_DL_mesh_layer_7),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -6, 48, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Arm_DL_1_mesh_layer_7),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -2, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Arm_DL_2_mesh_layer_7),
											GEO_CLOSE_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -2, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Arm_DL_3_mesh_layer_7),
											GEO_CLOSE_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Hand_DL_mesh_layer_7),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Left_Hand_Open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -6, -48, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 1),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT_INTER, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Arm_DL_1_mesh_layer_7),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -1, 1),
											GEO_OPEN_NODE(),
												GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT_INTER, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Arm_DL_2_mesh_layer_7),
											GEO_CLOSE_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -1, 1),
											GEO_OPEN_NODE(),
												GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT_INTER, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Arm_DL_3_mesh_layer_7),
											GEO_CLOSE_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Hand_DL_mesh_layer_7),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 13, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Open),
												GEO_BRANCH(1, cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Peace),
												GEO_BRANCH(1, cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Cap),
												GEO_BRANCH(1, cr_j355_Ice_Robo_Jess_Switch_Option_Ice_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, 37, NULL),
						GEO_OPEN_NODE(),
							GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, -1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Thigh_DL_mesh_layer_7),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Thigh_Color_mesh_layer_7),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 77, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Leg_mesh_layer_7),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 84, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Left_Shoe_mesh_layer_7),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, -37, NULL),
						GEO_OPEN_NODE(),
							GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, 1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Thigh_DL_mesh_layer_7),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 0, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Thigh_Color_mesh_layer_7),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT_INTER, 77, 0, 0, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Leg_mesh_layer_7),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_Ice_Robo_Jess_Switch_Option_Right_Shoe_DL_mesh_layer_7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Fludd_Switch_Option[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -33, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Fludd_Switch_Option_Fludd_DL_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Half__SHOES__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Closed__SHOES__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Robo_Eyes_Dead_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_mat_override_Robo_Eyes_Dead_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 40, 0, 0, cr_j355_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Right_Hand_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Hand_Switch_Option_Right_Hand_Cap_mesh_layer_2),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Hand_Switch_Option_Bulb_DL_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 59, 0, 0, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_2),
			GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 202, -26, 69),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Bulb_DL_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Hand_Wing_Cap_Switch_Option_Right_Hand_Wing_Cap_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Dead_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Dead_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Dead_3),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Dead_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Torso_skinned_mesh_layer_1),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 48, 0, 0, cr_j355_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Torso_mesh_layer_5),
						GEO_ASM(0, cr_j355_health_dial_func),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 61, 55, 0, 0, 0, -90),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 0, 0, 0, 0, cr_j355_2_Dial_Rot_DL_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_SWITCH_CASE(0, cr_j355_fludd_switch_func),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Fludd_Switch_Option),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_2),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Head_DL_mesh_layer_4),
												GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Bulb_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
											GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, 63, -7, 10, -148),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, -63, 7, -10, -148),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -6, 48, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Arm_DL_1_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -2, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Arm_DL_2_mesh_layer_4),
									GEO_CLOSE_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -2, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Arm_DL_3_mesh_layer_4),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Left_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -6, -48, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 1),
								GEO_OPEN_NODE(),
									GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Right_Arm_DL_1_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -1, 1),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Right_Arm_DL_2_mesh_layer_4),
									GEO_CLOSE_NODE(),
									GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -1, 1),
									GEO_OPEN_NODE(),
										GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Right_Arm_DL_3_mesh_layer_4),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 13, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Open),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Peace),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Cap),
										GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_cr_j355_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, 37, NULL),
				GEO_OPEN_NODE(),
					GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, -1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Thigh_DL_mesh_layer_4),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Thigh_Color_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 77, 0, 0, cr_j355_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Leg_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 84, 0, 0, cr_j355_Left_Shoe_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Left_Shoe_mesh_layer_4),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, -37, NULL),
				GEO_OPEN_NODE(),
					GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, 1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Thigh_DL_mesh_layer_4),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, cr_j355_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Thigh_Color_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 77, 0, 0, cr_j355_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Leg_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Shoe_DL_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Right_Shoe_DL_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Half__SHOES__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Closed__SHOES__1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Open__SHOES__2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1_mat_override_Robo_Eyes_Dead_3),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2_mat_override_Robo_Eyes_Dead_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4_mat_override_Robo_Eyes_Dead_3),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4_mat_override_Robo_Eyes_Dead_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout cr_j355_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 105),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 24576),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, cr_j355_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Torso_skinned_mesh_layer_1),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 48, 0, 0, cr_j355_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_Torso_mesh_layer_5),
												GEO_ASM(0, cr_j355_health_dial_func),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 61, 55, 0, 0, 0, -90),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0, cr_j355_2_Dial_Rot_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_SWITCH_CASE(0, cr_j355_fludd_switch_func),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, cr_j355_Fludd_Switch_Option),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Head_DL_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_Head_DL_mesh_layer_2),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Head_DL_mesh_layer_4),
																		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 142, -60, 0),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Bulb_DL_mesh_layer_4),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
																	GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, cr_j355_Capless_Head),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, 63, -7, 10, -148),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 98, -36, -63, 7, -10, -148),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -6, 48, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 0),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Arm_DL_1_mesh_layer_4),
														GEO_CLOSE_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -2, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Arm_DL_2_mesh_layer_4),
															GEO_CLOSE_NODE(),
															GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -2, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Arm_DL_3_mesh_layer_4),
															GEO_CLOSE_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Left_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, cr_j355_Left_Hand_Open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -6, -48, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 40, -1, 1),
														GEO_OPEN_NODE(),
															GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 0, 0, 0, cr_j355_Right_Arm_DL_1_mesh_layer_4),
														GEO_CLOSE_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 76, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 3, -1, 1),
															GEO_OPEN_NODE(),
																GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 0, 0, 0, cr_j355_Right_Arm_DL_2_mesh_layer_4),
															GEO_CLOSE_NODE(),
															GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 43, -1, 1),
															GEO_OPEN_NODE(),
																GEO_BILLBOARD_WITH_PARAMS_AND_DL(LAYER_ALPHA, 0, 0, 0, cr_j355_Right_Arm_DL_3_mesh_layer_4),
															GEO_CLOSE_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 57, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Right_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 13, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, cr_j355_Right_Hand_Open),
																GEO_BRANCH(1, cr_j355_Right_Hand_Peace),
																GEO_BRANCH(1, cr_j355_Right_Hand_Cap),
																GEO_BRANCH(1, cr_j355_Right_Hand_Wing_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, 37, NULL),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, -1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Thigh_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, cr_j355_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Thigh_Color_mesh_layer_4),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 77, 0, 0, cr_j355_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Leg_mesh_layer_4),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 0, cr_j355_Left_Shoe_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Left_Shoe_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -5, -37, NULL),
										GEO_OPEN_NODE(),
											GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 1, 0, 1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Thigh_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, cr_j355_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Thigh_Color_mesh_layer_4),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 77, 0, 0, cr_j355_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Leg_mesh_layer_4),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_Right_Shoe_DL_mesh_layer_1),
															GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_Right_Shoe_DL_mesh_layer_4),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, cr_j355_B_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, cr_j355_Ice_Robo_Jess),
							GEO_BRANCH(1, cr_j355_Ice_Robo_Jess),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cr_j355_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, cr_j355_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, cr_j355_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cr_j355_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, cr_j355_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
