extern const GeoLayout cr_particle_snowflake_Anim_Switch_opt1[];
extern const GeoLayout cr_particle_snowflake_Anim_Switch_opt2[];
extern const GeoLayout cr_particle_snowflake_Anim_Switch_opt3[];
extern const GeoLayout cr_particle_snowflake_Anim_Switch_opt4[];
extern const GeoLayout cr_particle_snowflake_Anim_Switch_opt5[];
extern const GeoLayout cr_particle_snowflake_geo[];
extern u8 cr_particle_snowflake_snowflake6_rgba16[];
extern u8 cr_particle_snowflake_snowflake5_rgba16[];
extern u8 cr_particle_snowflake_snowflake4_rgba16[];
extern u8 cr_particle_snowflake_snowflake3_rgba16[];
extern u8 cr_particle_snowflake_snowflake2_rgba16[];
extern u8 cr_particle_snowflake_snowflake1_rgba16[];
extern Vtx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_vtx_0[4];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_tri_0[];
extern Gfx mat_cr_particle_snowflake_snow1[];
extern Gfx mat_revert_cr_particle_snowflake_snow1[];
extern Gfx mat_cr_particle_snowflake_snow2[];
extern Gfx mat_revert_cr_particle_snowflake_snow2[];
extern Gfx mat_cr_particle_snowflake_snow3[];
extern Gfx mat_revert_cr_particle_snowflake_snow3[];
extern Gfx mat_cr_particle_snowflake_snow4[];
extern Gfx mat_revert_cr_particle_snowflake_snow4[];
extern Gfx mat_cr_particle_snowflake_snow5[];
extern Gfx mat_revert_cr_particle_snowflake_snow5[];
extern Gfx mat_cr_particle_snowflake_snow6[];
extern Gfx mat_revert_cr_particle_snowflake_snow6[];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4[];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_mat_override_snow2_0[];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_mat_override_snow3_1[];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_mat_override_snow4_2[];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_mat_override_snow5_3[];
extern Gfx cr_particle_snowflake_Snowflake_DL_mesh_layer_4_mat_override_snow6_4[];
