extern const GeoLayout cr_j355_cap_ice_wing_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout cr_j355_cap_ice_wing_geo[];
extern u8 cr_j355_cap_ice_wing_j355_arm_segment_ice_rgba16[];
extern u8 cr_j355_cap_ice_wing_jess_ice_new_rgba16[];
extern u8 cr_j355_cap_ice_wing_wing_ice_rgba16[];
extern Vtx cr_j355_cap_ice_wing_Bulb_DL_mesh_layer_7_vtx_0[4];
extern Gfx cr_j355_cap_ice_wing_Bulb_DL_mesh_layer_7_tri_0[];
extern Vtx cr_j355_cap_ice_wing_Ice_Wing_Cap_DL_mesh_layer_7_vtx_0[61];
extern Gfx cr_j355_cap_ice_wing_Ice_Wing_Cap_DL_mesh_layer_7_tri_0[];
extern Vtx cr_j355_cap_ice_wing_Ice_Wing_Cap_DL_mesh_layer_7_vtx_1[8];
extern Gfx cr_j355_cap_ice_wing_Ice_Wing_Cap_DL_mesh_layer_7_tri_1[];
extern Gfx mat_cr_j355_cap_ice_wing_Ice_Cutout[];
extern Gfx mat_revert_cr_j355_cap_ice_wing_Ice_Cutout[];
extern Gfx mat_cr_j355_cap_ice_wing_Ice_Env_Map[];
extern Gfx mat_revert_cr_j355_cap_ice_wing_Ice_Env_Map[];
extern Gfx mat_cr_j355_cap_ice_wing_Ice_Wing[];
extern Gfx mat_revert_cr_j355_cap_ice_wing_Ice_Wing[];
extern Gfx cr_j355_cap_ice_wing_Bulb_DL_mesh_layer_7[];
extern Gfx cr_j355_cap_ice_wing_Ice_Wing_Cap_DL_mesh_layer_7[];
extern Gfx cr_j355_cap_ice_wing_material_revert_render_settings[];
