extern const GeoLayout cr_davy_cap_fire_star_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout cr_davy_cap_fire_star_geo[];
extern u8 cr_davy_cap_fire_star_DavyMagma_rgba16[];
extern Vtx cr_davy_cap_fire_star_Winged_Metal_Cap_DL_mesh_layer_1_vtx_0[134];
extern Gfx cr_davy_cap_fire_star_Winged_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_cr_davy_cap_fire_star_Magma[];
extern Gfx mat_revert_cr_davy_cap_fire_star_Magma[];
extern Gfx cr_davy_cap_fire_star_Winged_Metal_Cap_DL_mesh_layer_1[];
extern Gfx cr_davy_cap_fire_star_material_revert_render_settings[];
